[project]
name = "sikorius"
version = "0.1.0"
description = "Aplicación con interfaz gráfica para crear, visualizar y usar modelos de regresión lineal a partir de CSV, Excel y SQLite"
readme = "README.md"
authors = [
    { name = "xabier.pcabanas", email = "xabier.pcabanas@udc.es" }
]
requires-python = ">=3.12"
dependencies = []

[project.scripts]
sikorius = "sikorius:main"

[build-system]
requires = ["uv_build>=0.12.21,<0.13.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest>=9.1.1",
]
